### ISSUE TITLE
This is sometimes causing test failing due to mismatch between mocked data and returned data of `updatedAt`

### ISSUE THREAD

**Issue by abayo-luc** [tabiya-tech/taxonomy-model-application#128]
https://github.com/tabiya-tech/taxonomy-model-application/blame/77d9e16fc6f593d66ddab5b4ab678759b43381ee/frontend/src/modelInfo/modelInfo.service.test.ts#L63

**Comment by ApostolosBenisis** [comment]
most likely fixed with: 
https://github.com/tabiya-tech/taxonomy-model-application/commit/60ca999f1083c5bac34082620e9f2adf81353837
"fix: modelInfo.service.ts transform incorrectly maps createdAt to updatedAt value"
